# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-12-29 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
